/* SPDX-License-Identifier: MPL-2.0
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * © Copyright 2026 Technical University of Denmark
 * Lead developer: Leonardo Ferhati
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, it, expect } from 'vitest'
import {
  budgetDepletionYear, budgetYears, cumulativeConsumedAt,
  remainingBudgetAt, remainingBudgetSeries,
} from '../src/utils/carbonBudget'
import type { CarbonBudgetConfig } from '../src/api/client'
import fixture from './fixtures/carbonBudgetSparkline.json'

// The AESA sidebar's budget sparkline was a FOURTH copy of the depletion
// arithmetic (after the engine, the timeline inset fixed in the previous patch,
// and the helper itself). It accumulated INCLUSIVELY —
//
//     cum += projected_emissions[y]   // then read AT y
//
// — while `CarbonBudgetConfig.remaining_budget(year)` sums
// `range(start_year, year)`, EXCLUDING the current year. So it annotated
// depletion one year early on every configuration: "depleted ~2030" in the
// sidebar against 2031 from the engine and from the timeline inset, two panels
// apart in the same session.
//
// Unlike the timeline inset, this preview CANNOT read `remaining_budget_gt` —
// it renders before any compute, live as the user changes the budget and SSP
// dropdowns, with no SR rows in existence. So the rule is re-implemented in
// `utils/carbonBudget.ts` and checked against the ENGINE'S OWN OUTPUT here: the
// fixture is generated by the backend from `remaining_budget`, across all four
// AR6 budget options at SSP2-4.5.

type Fx = {
  budget_option_id: string
  ssp_id: string
  initial_budget_gt: number
  start_year: number
  end_year: number
  projected_emissions: Record<string, number>
  rows: Array<{ year: number; remaining_gt: number }>
  engine_depletion_year: number | null
  pre_fix_sparkline_depletion_year: number | null
}

const PAIRINGS = [
  'IPCC_AR6_1p5C_50__SSP2-4.5',
  'IPCC_AR6_1p5C_67__SSP2-4.5',
  'IPCC_AR6_2C_50__SSP2-4.5',
  'IPCC_AR6_2C_67__SSP2-4.5',
] as const

function budgetOf(fx: Fx): CarbonBudgetConfig {
  const emissions: Record<number, number> = {}
  for (const [y, v] of Object.entries(fx.projected_emissions)) emissions[Number(y)] = v
  return {
    initial_budget_gt: fx.initial_budget_gt,
    start_year: fx.start_year,
    end_year: fx.end_year,
    ssp_scenario: fx.ssp_id,
    budget_source: fx.budget_option_id,
    projected_emissions: emissions,
  } as any
}

// ── the gate: agree with the engine on every shipped pairing ────────────────

describe.each(PAIRINGS)('%s', (key) => {
  const fx = (fixture as any)[key] as Fx
  const budget = budgetOf(fx)

  it('depletion year equals the engine\'s', () => {
    expect(fx.engine_depletion_year).not.toBeNull()   // fixture sanity
    expect(budgetDepletionYear(budget)).toBe(fx.engine_depletion_year)
  })

  it('is NOT the year the inclusive-accumulating sparkline produced', () => {
    // The bug as a number. 1.5 °C/67 × SSP2-4.5 is the one that was reported:
    // the sidebar read "depleted ~2030" where the engine says 2031.
    expect(fx.engine_depletion_year! - fx.pre_fix_sparkline_depletion_year!).toBe(1)
    expect(budgetDepletionYear(budget)).not.toBe(fx.pre_fix_sparkline_depletion_year)
  })

  it('every remaining-budget point matches the engine exactly', () => {
    const series = remainingBudgetSeries(budget)
    expect(series).toHaveLength(fx.rows.length)
    for (const [i, p] of series.entries()) {
      expect(p.year).toBe(fx.rows[i].year)
      expect(p.remaining).toBeCloseTo(fx.rows[i].remaining_gt, 9)
    }
  })

  it('remainingBudgetAt agrees row for row', () => {
    for (const row of fx.rows) {
      expect(remainingBudgetAt(budget, row.year)).toBeCloseTo(row.remaining_gt, 9)
    }
  })
})

// ── the rule itself ─────────────────────────────────────────────────────────

describe('the sum is exclusive of the current year', () => {
  const budget = {
    initial_budget_gt: 100,
    start_year: 2025,
    end_year: 2030,
    ssp_scenario: 'test',
    budget_source: 'test',
    projected_emissions: { 2025: 10, 2026: 20, 2027: 30, 2028: 40, 2029: 50, 2030: 60 },
  } as any as CarbonBudgetConfig

  it('the first year has consumed nothing yet', () => {
    expect(cumulativeConsumedAt(budget, 2025)).toBe(0)
    expect(remainingBudgetAt(budget, 2025)).toBe(100)
  })

  it('each year excludes its own emissions', () => {
    expect(cumulativeConsumedAt(budget, 2026)).toBe(10)          // 2025 only
    expect(cumulativeConsumedAt(budget, 2027)).toBe(30)          // 2025+2026
    expect(remainingBudgetAt(budget, 2027)).toBe(70)
  })

  it('depletes at the first year remaining reaches zero', () => {
    // consumed: 2025→0, 2026→10, 2027→30, 2028→60, 2029→100 ⇒ remaining 0.
    // Inclusive accumulation would have flagged 2028 (10+20+30+40 = 100).
    expect(budgetDepletionYear(budget)).toBe(2029)
  })

  it('clamps at zero rather than going negative', () => {
    expect(remainingBudgetAt(budget, 2030)).toBe(0)
  })

  it('ignores years outside the horizon, as the engine does', () => {
    const wide = { ...budget, projected_emissions: { 2020: 999, ...budget.projected_emissions, 2099: 999 } } as any
    expect(budgetYears(wide)).toEqual([2025, 2026, 2027, 2028, 2029, 2030])
    expect(cumulativeConsumedAt(wide, 2026)).toBe(10)  // 2020's 999 excluded
  })

  it('returns null when the budget is never exhausted', () => {
    const roomy = { ...budget, initial_budget_gt: 10_000 } as any
    expect(budgetDepletionYear(roomy)).toBeNull()
  })

  it('pins the FIRST crossing even when net negatives replenish later', () => {
    // Overshoot is committed; replenishment does not un-commit it.
    const rebound = {
      ...budget, initial_budget_gt: 25,
      projected_emissions: { 2025: 10, 2026: 20, 2027: -40, 2028: -40, 2029: -40, 2030: -40 },
    } as any
    // consumed: 2025→0, 2026→10, 2027→30 ⇒ remaining 0 at 2027; then it climbs.
    expect(budgetDepletionYear(rebound)).toBe(2027)
    expect(remainingBudgetAt(rebound, 2030)).toBeGreaterThan(0)
  })
})
