# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# © Copyright 2026 Technical University of Denmark
# Lead developer: Leonardo Ferhati

"""Phase B changed NO computed value. This is the assertion.

Phase B was a documentation and labelling pass over the carbon-budget system,
plus test hardening. It touched files that compute — `aesa_engine.py` (a new
`carbon_budget_vintage()`, a rewritten `co2e_conversion.source` string),
`aesa_schemas.py` (two `provisional` defaults flipped), `api/aesa.py` (the export
now basis-applies) — so "nothing computed moved" has to be checked, not asserted
in a commit message.

`tests/fixtures/phase_b_no_drift.json` was generated by the probe reproduced
below, run against **main @ aa4453b, before any Phase B change**. Every number
the carbon-budget path produces is in it:

* the four per-budget CO2->CO2e factors;
* for all 4 budgets x both bases: the basis-applied initial budget, the
  remaining-budget and per-year-allocation series at 5-year steps across
  2025-2100, the depletion year, `provisional`, and `start_year`;
* the FULL SR result set from `AESAEngine.compute` on the default config — SR,
  allocated SOS, impact, `remaining_budget_gt`, `global_allocation_gt` and the
  total sharing factor for every (year, boundary) row, on both bases.

A failure here means a Phase B edit changed a number. That may be correct — but
it is then a methodological change and needs to be argued for, not absorbed as a
side effect of a docs patch.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from mapper.core.aesa_engine import (
    AESAEngine,
    build_carbon_budget,
    build_default_sharing_preset,
    co2e_factor_for_budget,
    load_boundary_sets,
    load_carbon_budget_options,
    suggest_method_mapping,
)
from mapper.models.aesa_schemas import AESAConfiguration
from mapper.models.bom_schemas import (
    DSMLCAResult,
    DSMLCASummary,
    DSMLCAYearResult,
    ImpactAssessmentMeta,
    ImpactAssessmentResult,
)

GOLDEN = json.loads(
    (Path(__file__).parent / "fixtures" / "phase_b_no_drift.json").read_text(encoding="utf-8"))

# The first two are EpC- and AGR-allocated. The last three are the ONLY
# AR-allocated boundaries in MULTI_D_DEFAULTS, and they are here because the
# golden was blind without them: layer 1's AR pair was the one sharing value no
# covered row depended on, so it could be re-sourced -- scope, vintage, window
# and all -- with this file still green. Found while auditing that pair; the
# gap is independent of what AR is eventually defined as, which is why it is
# closed here and the data question is not touched.
METHODS = [["EF v3.1", "climate change", "global warming potential (GWP100)"],
           ["EF v3.1", "acidification", "accumulated exceedance (AE)"],
           ["EF v3.1", "ozone depletion", "ozone depletion potential (ODP)"],
           ["EF v3.1", "particulate matter formation", "impact on human health"],
           ["EF v3.1", "photochemical oxidant formation: human health",
            "tropospheric ozone concentration increase"]]
IMPACT_SCALES = (6.0e12, 1.0e9, 2.0e4, 1.0e2, 5.0e10)
PROBE_YEARS = list(range(2025, 2101, 5))


def _impact_envelope() -> ImpactAssessmentResult:
    def years(scale: float) -> list[DSMLCAYearResult]:
        return [DSMLCAYearResult(year=y, total_impact=scale + y, unit="u",
                                 impact_by_cohort={"BEV": scale + y},
                                 impact_by_material={}, count_by_cohort={"BEV": 10})
                for y in (2025, 2030, 2035, 2040)]

    return ImpactAssessmentResult(
        task_id="t",
        meta=ImpactAssessmentMeta(mode="static", mfa_system_id="sys", scope="all",
                                  methods=METHODS),
        results=[DSMLCAResult(mfa_system_id="sys", method=m, method_label=" | ".join(m),
                              scope="all", unit="u", years=years(sc),
                              summary=DSMLCASummary(total_impact=0.0, peak_year=2025,
                                                    peak_impact=0.0))
                 for m, sc in zip(METHODS, IMPACT_SCALES)])


def test_the_golden_file_is_not_vacuous():
    """A fixture of empty series would make every assertion below pass."""
    assert len(GOLDEN["factors"]) == 4
    n_rows = len(METHODS) * 4          # methods x fleet years
    assert len(GOLDEN["SR|CO2"]) == n_rows
    assert len(GOLDEN["SR|CO2e_GHG"]) == n_rows
    # Coverage, not just row count: an SR set that happens to omit the
    # AR-allocated boundaries is how the layer-1 AR pair went unguarded.
    covered = {r[1] for r in GOLDEN["SR|CO2"]}
    assert {"ozone_depletion", "particulate_matter",
            "photochemical_ozone_formation"} <= covered, (
        "the golden no longer covers every AR-allocated boundary")
    assert GOLDEN["IPCC_AR6_2C_50|CO2"]["remaining"], "no remaining-budget series"
    # It must actually exercise the CO2e path, or the basis half is untested.
    assert all(f > 1.0 for f in GOLDEN["factors"].values())
    assert (GOLDEN["IPCC_AR6_2C_50|CO2e_GHG"]["initial"]
            != GOLDEN["IPCC_AR6_2C_50|CO2"]["initial"])


def test_the_per_budget_factors_did_not_move():
    for bid, opt in {o["id"]: o for o in load_carbon_budget_options()}.items():
        assert co2e_factor_for_budget(opt) == pytest.approx(
            GOLDEN["factors"][bid], rel=1e-15), f"{bid} factor moved"


@pytest.mark.parametrize("bid", [
    "IPCC_AR6_1p5C_50", "IPCC_AR6_1p5C_67", "IPCC_AR6_2C_50", "IPCC_AR6_2C_67"])
@pytest.mark.parametrize("basis", ["CO2", "CO2e_GHG"])
def test_the_budget_series_did_not_move(bid, basis):
    want = GOLDEN[f"{bid}|{basis}"]
    cb = build_carbon_budget(budget_option_id=bid).model_copy(
        update={"budget_basis": basis})
    applied = cb.with_basis_applied()

    assert applied.initial_budget_gt == pytest.approx(want["initial"], rel=1e-15)
    assert cb.start_year == want["start_year"]
    assert cb.provisional == want["provisional"]
    for y in PROBE_YEARS:
        assert applied.remaining_budget(y) == pytest.approx(
            want["remaining"][str(y)], rel=1e-15), f"{bid}/{basis} remaining @ {y}"
        assert applied.annual_global_allocation(y) == pytest.approx(
            want["alloc"][str(y)], rel=1e-15), f"{bid}/{basis} allocation @ {y}"

    depletion = next((y for y in range(2025, 2101)
                      if applied.remaining_budget(y) <= 0), None)
    assert depletion == want["depletion"], f"{bid}/{basis} depletion year moved"


@pytest.mark.parametrize("basis", ["CO2", "CO2e_GHG"])
def test_the_full_sr_result_did_not_move(basis):
    """The end-to-end pipeline, not just the budget helpers."""
    bset = load_boundary_sets()["Sala2020_EF"]
    cfg = AESAConfiguration(
        id="c", name="c", mfa_system_id="sys", sharing=build_default_sharing_preset(),
        method_mapping=suggest_method_mapping(METHODS, bset),
        carbon_budget=build_carbon_budget().model_copy(update={"budget_basis": basis}),
        created_at="2025-01-01T00:00:00Z")
    res = AESAEngine.compute(_impact_envelope().results, cfg, bset)

    got = sorted((r.year, r.pb_id, r.sr, r.allocated_sos, r.impact,
                  r.remaining_budget_gt, r.global_allocation_gt,
                  r.total_sharing_factor) for r in res.results)
    want = GOLDEN[f"SR|{basis}"]
    assert len(got) == len(want)
    for g, w in zip(got, want):
        assert g[0] == w[0] and g[1] == w[1], "row set changed"
        for i, name in enumerate(
                ["sr", "allocated_sos", "impact", "remaining_budget_gt",
                 "global_allocation_gt", "total_sharing_factor"], start=2):
            if w[i] is None:
                assert g[i] is None, f"{g[0]}/{g[1]} {name}: None -> {g[i]}"
            else:
                assert g[i] == pytest.approx(w[i], rel=1e-15), (
                    f"{g[0]}/{g[1]} {name} moved: {g[i]} != {w[i]}")


def test_the_co2e_basis_still_divides_the_climate_sr_by_f():
    """The relationship the golden numbers encode, stated independently: a
    Phase B change that scaled both sides equally would slip past a pure
    golden-file diff."""
    f = co2e_factor_for_budget(
        {o["id"]: o for o in load_carbon_budget_options()}["IPCC_AR6_2C_50"])
    by_basis = {}
    for basis in ("CO2", "CO2e_GHG"):
        by_basis[basis] = {
            (r[0], r[1]): r[2] for r in GOLDEN[f"SR|{basis}"]}
    for key, sr_co2 in by_basis["CO2"].items():
        sr_co2e = by_basis["CO2e_GHG"][key]
        if key[1] == "climate_change":
            assert sr_co2e == pytest.approx(sr_co2 / f, rel=1e-12)
        else:
            assert sr_co2e == pytest.approx(sr_co2, rel=1e-15), (
                "a non-climate boundary responded to the budget basis"
            )


# ── The probe ───────────────────────────────────────────────────────────────
#
# `python -m tests.test_phase_b_no_drift <provenance>` rewrites the fixture
# from a live run. The module docstring has always said the golden "was
# generated by the probe reproduced below"; until AR was re-sourced there was
# no probe, only prose describing one, so the file could only be regenerated by
# hand -- which is the one way a golden must never be produced.
#
# Regenerating is a deliberate act. It asserts "these numbers moved and the
# move is intended", so the provenance argument is required and lands in
# `_generated_from` next to the numbers it explains.

def _probe() -> dict:
    out: dict = {"factors": {}}
    options = {o["id"]: o for o in load_carbon_budget_options()}
    for bid, opt in options.items():
        out["factors"][bid] = co2e_factor_for_budget(opt)
    for bid in options:
        for basis in ("CO2", "CO2e_GHG"):
            cb = build_carbon_budget(budget_option_id=bid).model_copy(
                update={"budget_basis": basis})
            applied = cb.with_basis_applied()
            out[f"{bid}|{basis}"] = {
                "initial": applied.initial_budget_gt,
                "start_year": cb.start_year,
                "provisional": cb.provisional,
                "remaining": {str(y): applied.remaining_budget(y) for y in PROBE_YEARS},
                "alloc": {str(y): applied.annual_global_allocation(y) for y in PROBE_YEARS},
                "depletion": next((y for y in range(2025, 2101)
                                   if applied.remaining_budget(y) <= 0), None),
            }
    bset = load_boundary_sets()["Sala2020_EF"]
    for basis in ("CO2", "CO2e_GHG"):
        cfg = AESAConfiguration(
            id="c", name="c", mfa_system_id="sys", sharing=build_default_sharing_preset(),
            method_mapping=suggest_method_mapping(METHODS, bset),
            carbon_budget=build_carbon_budget().model_copy(update={"budget_basis": basis}),
            created_at="2025-01-01T00:00:00Z")
        res = AESAEngine.compute(_impact_envelope().results, cfg, bset)
        out[f"SR|{basis}"] = sorted(
            [r.year, r.pb_id, r.sr, r.allocated_sos, r.impact, r.remaining_budget_gt,
             r.global_allocation_gt, r.total_sharing_factor] for r in res.results)
    return out


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        raise SystemExit(
            "usage: python -m tests.test_phase_b_no_drift '<why these numbers moved>'")
    data = _probe()
    data["_generated_from"] = sys.argv[1]
    path = Path(__file__).parent / "fixtures" / "phase_b_no_drift.json"
    path.write_text(json.dumps(data, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(data['SR|CO2'])} SR rows)")
